### ISSUE TITLE
Feature Request - Pass in filepath to local graphql schema

### ISSUE THREAD

**Issue by criles25** [apollographql/apollo-workbench-vscode#127]
When adding a subgraph to Apollo Workbench, we would like to be able to pass the filepath to a local schema file. 

Ideally, it would be something that we configure in a subgraph's settings

For example, have a property like `"schema": "./path-to-valid-sdl"`.

**Comment by michael-watson** [comment]
@criles25 Apologies for the delay, I've been looking into this through another path actually. I've been exploring the option of being able to point your workbench design at a [Rover yaml file](https://www.apollographql.com/docs/rover/supergraphs/#configuration) which would enable what you're asking for. I have a couple questions for you on this:

1. Do you currently use the [rover config files](https://www.apollographql.com/docs/rover/supergraphs/#configuration) today? 
2. If yes, would you prefer to use the rover file directly instead of defining schema pointers in a workbench file?
3. If no, can you help me understand a little more of what you're trying to accomplish with the separate schema files?
- Are you trying to point at the schema files that live in separate `git` repos?
- Are you trying to use a mix of local schema files and schemas defined in the workbench file? Or are you trying to only have schema files to work with
- Is this related to "change management" as your design evolve? 
- Are you committing your workbench file to a master repository or is this is a short lived file (you toss is after design is implemented)?

I think there is a lot connected to this request and I'm planning on addressing it for sure. Just want to find the best way to handle this and make sure I have full scope of how you're using it. This is a common ask from others also!

**Comment by michael-watson** [comment]
Workbench now supports the router config files directly 🎉

Feel free to reopen another issue if you have problems with file pointers
